blank_issues_enabled: false
contact_links:
  - name: ğŸ“š ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/t-tsuji/diopside/blob/main/README.md
    about: ã¾ãšãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã‚’ã”ç¢ºèªãã ã•ã„
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/t-tsuji/diopside/discussions
    about: ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ã§è³ªå•ã‚„ã‚¢ã‚¤ãƒ‡ã‚¢ã‚’è­°è«–ã—ã¦ãã ã•ã„
